export const ROUTES = {
  health: '/health',
  status: '/status',
  openaiAuthStatus: '/providers/openai/auth/status',
  openaiAuthMode: '/providers/openai/auth/mode',
  openaiAuthApiKey: '/providers/openai/auth/api-key',
  openaiAuthApiKeyVerify: '/providers/openai/auth/api-key/verify',
  openaiAuthChatGPTActivate: '/providers/openai/auth/chatgpt/activate',
  sessions: '/sessions',
  sessionsLatest: '/sessions/latest',
  sessionsLatestResume: '/sessions/latest/resume',
  sessionById: (id: string) => `/sessions/${id}`,
  sessionResume: (id: string) => `/sessions/${id}/resume`,
  sessionPrompt: (id: string) => `/sessions/${id}/prompt`,
  sessionPromptStream: (id: string) => `/sessions/${id}/prompt/stream`,
  sessionAgentActivity: (id: string) => `/sessions/${id}/agents/activity`,
  sessionProjectSelect: (id: string) => `/sessions/${id}/project/select`,
  sessionProjectContext: (id: string) => `/sessions/${id}/project/context`,
  sessionSystemAction: (id: string, action: string) => `/sessions/${id}/system-actions/${action}`,
  sessionToolListDir: (id: string) => `/sessions/${id}/tools/list_dir`,
  sessionToolReadFile: (id: string) => `/sessions/${id}/tools/read_file`,
  sessionToolSearchText: (id: string) => `/sessions/${id}/tools/search_text`,
  sessionToolWriteFile: (id: string) => `/sessions/${id}/tools/write_file`,
  sessionToolRunCommandSafe: (id: string) => `/sessions/${id}/tools/run_command_safe`,
  projects: '/projects',
  settings: '/settings',
  settingByKey: (key: string) => `/settings/${encodeURIComponent(key)}`,
  systemActions: '/system-actions',
  approvals: '/approvals',
  approvalApprove: (id: string) => `/approvals/${id}/approve`,
  approvalReject: (id: string) => `/approvals/${id}/reject`,
  eventsStream: '/events/stream'
} as const
